version: "3.3"
services:
  app:
    build: ./FlaskApp
    depends_on:
      - db
    ports:
      - "5002:5002"
    environment:
      MYSQL_DATABASE_USER: root
      MYSQL_DATABASE_PASSWORD: root
      MYSQL_DATABASE_DB: BucketList
      MYSQL_DATABASE_HOST: db


  db:
    build: ./MySQL_Queries
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
