version: "3.3"
services:
  app:
    build: ./FlaskApp
    depends_on:
      - db
    ports:
      - "5002:5002"
    environment:
      MYSQL_DATABASE_USER: root
      MYSQL_DATABASE_PASSWORD: root
      MYSQL_DATABASE_DB: BucketList
      MYSQL_DATABASE_HOST: db


  db:
    build: ./MySQL_Queries
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root